services:
  postgres:
    build:
      dockerfile: Dockerfile.postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8
    ports:
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    restart: always

  redis:
    image: redis:7
    restart: always

  maildev:
    image: maildev/maildev
    # command: --auto-relay
    ports:
      - 1080:1080
    environment:
      - MAILDEV_INCOMING_USER=${EMAIL_SMTP_USER}
      - MAILDEV_INCOMING_PASS=${EMAIL_SMTP_PASSWORD}
    env_file:
      - .env.maildev
    restart: always

  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/directus && /usr/bin/minio server --console-address :9001 /data'
    ports:
      - 9001:9001
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=${ADMIN_EMAIL}
      - MINIO_ROOT_PASSWORD=${ADMIN_PASSWORD}
    restart: always

  directus:
    image: directus/directus:11.0.0-rc.3
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
      - maildev
