services:
  postgres:
    build:
      dockerfile: Dockerfile.postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8
    ports:
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    restart: always

  redis:
    image: redis:7
    restart: always

  maildev:
    image: maildev/maildev
    # command: --auto-relay
    ports:
      - 1080:1080
    environment:
      - MAILDEV_INCOMING_USER=${EMAIL_SMTP_USER}
      - MAILDEV_INCOMING_PASS=${EMAIL_SMTP_PASSWORD}

      - MAILDEV_OUTGOING_HOST
      - MAILDEV_OUTGOING_PORT
      - MAILDEV_OUTGOING_USER
      - MAILDEV_OUTGOING_PASS
      - MAILDEV_OUTGOING_SECURE=true
    restart: always

  directus:
    image: directus/directus:10
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    environment:
      - PUBLIC_URL

      - SECRET
      - LOG_LEVEL

      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - CACHE_ENABLED=true
      - CACHE_AUTO_PURGE=true
      - CACHE_STORE=redis

      - EMAIL_FROM
      - EMAIL_TRANSPORT=smtp
      - EMAIL_SMTP_HOST
      - EMAIL_SMTP_PORT
      - EMAIL_SMTP_USER
      - EMAIL_SMTP_PASSWORD

      - WEBSOCKETS_ENABLED=true

      - ADMIN_EMAIL
      - ADMIN_PASSWORD

    restart: always
    depends_on:
      - postgres
      - redis
