FROM postgres:16

RUN apt-get update && apt-get upgrade -y && apt-get install postgresql-16-postgis-3 -y && rm -rf /var/lib/apt/lists/*

RUN echo 'CREATE EXTENSION IF NOT EXISTS postgis;' > /docker-entrypoint-initdb.d/init-postgis.sql